[package]
name = "zksync_prover"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_state = { path = "../../lib/state", version = "1.0" }
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_circuit = { path = "../../lib/circuit", version = "1.0" }
zksync_crypto = { path = "../../lib/crypto", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }
zksync_prover_utils = { path = "../../lib/prover_utils", version = "1.0" }

hex = "0.4"
rust-crypto = "0.2"
web3 = "0.13.0"
tokio = "0.1.18"

serde = "1.0.90"
serde_json = "1.0.0"
num = { version = "0.2", features = ["serde"] }
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
log = "0.4"
env_logger = "0.6"
reqwest = { version = "0.10", features = ["blocking", "json"] }
anyhow = "1.0"
backoff = "0.1.6"
structopt = "0.3.20"
ctrlc = { version = "3.1", features = ["termination"] }
