[workspace]
members = [
    "core/data_restore",
    "core/key_generator",
    "core/eth_client",
    "core/plasma",
    "core/server",
    "core/storage",
    "core/circuit",
    "core/models",
    "core/prover",
    "core/key_generator",
    "core/spec_test",
    "core/testkit",
    "core/loadtest",
    "core/crypto_exports"
]
