[package]

name = "franlklin"
version = "0.1.0"
edition = "2018"

authors = [
    "Alex Gluchowski <alex@gluchowski.net>",
    "Alex Vlasov <alex.m.vlasov@gmail.com>"
]

[dependencies]
eth_client = { path = "src/eth_client" }
plasma = { path = "src/plasma" }
models = { path = "src/models" }
storage = { path = "src/storage" }
prover = { path = "src/prover" }
server = { path = "src/server" }

signal-hook = { version = "0.1.8", features = ["tokio-support"] }
tokio = "0.1.18"
futures = "0.1.25"