[workspace]
members = [
    "core/data_restore",
    "core/key_generator",
    "core/merkle_tree",
    "core/eth_client",
    "core/models",
    "core/plasma",
    "core/prover",
    "core/server",
    "core/storage",
]
