version: '3.2'
services:
  postgres:
    image: "postgres:12"
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust

  rskj:
    build:
      context: ./docker/rskj
  
  
  dev-ticker:
    image: "matterlabs/dev-ticker:latest"
    volumes:
      - ./etc/tokens/:/etc/tokens

  dev-liquidity-token-watcher:
    image: "matterlabs/dev-liquidity-token-watcher:latest"
    env_file:
      - ./etc/env/docker.env
    volumes:
      - ./etc/tokens/:/etc/tokens

  zk:
    build:
      context: ./docker/zk-environment 
    depends_on:
      - postgres
      - rskj
      - dev-ticker
      - dev-liquidity-token-watcher
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/zksync
      - /usr/src/cache:/usr/src/cache
      - /usr/src/keys:/usr/src/keys
    environment:
      - IN_DOCKER=true
      - CACHE_DIR=/usr/src/cache
      - SCCACHE_CACHE_SIZE=50g
      - CI=1
      - CAROOT=/usr/src/zksync
      - NODE_EXTRA_CA_CERTS=/usr/src/zksync/rootCA.pem
