version: '3.2'
services:
  postgres:
    image: "postgres:12"
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust

  geth:
    image: "matterlabs/geth:latest"
    environment:
      - PLUGIN_CONFIG=fast

  dev-ticker:
    image: "matterlabs/dev-ticker:latest"
    volumes:
      - ./etc/tokens/:/etc/tokens

  dev-liquidity-token-watcher:
    image: "matterlabs/dev-liquidity-token-watcher:latest"
    env_file:
      - ./etc/env/docker.env
    volumes:
      - ./etc/tokens/:/etc/tokens

  zk:
    image: "matterlabs/zk-environment:latest"
    depends_on:
      - postgres
      - geth
      - dev-ticker
      - dev-liquidity-token-watcher
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/zksync
      - /usr/src/cache:/usr/src/cache
      - /usr/src/keys:/usr/src/keys
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_GCS_KEY_PATH:-/etc/sa_secret/sa_key.json}:/etc/sa_secret/sa_key.json
    environment:
      - IN_DOCKER=true
      - CACHE_DIR=/usr/src/cache
      - SCCACHE_CACHE_SIZE=50g
      - SCCACHE_GCS_BUCKET=sccache-zksync-ci
      - SCCACHE_GCS_KEY_PATH=/etc/sa_secret/sa_key.json
      - SCCACHE_GCS_RW_MODE=READ_WRITE
      - CI=1
