version: '3.2'
services:
  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    volumes:
    - type: bind
      source: ./volumes/postgres
      target: /var/lib/postgresql/data
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
  geth:
    image: "matterlabs/geth:latest"
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
    - type: bind
      source: ./volumes/geth
      target: /var/lib/geth/data
  dev-ticker:
    image: "matterlabs/dev-ticker:latest"
    ports:
      - "9876:9876"
  tesseracts:
    image: "adria0/tesseracts"
    command: --cfg /tesseracts.toml -vvv
    ports:
      - "8000:8000"
    volumes:
    - ./etc/tesseracts/tesseracts.toml:/tesseracts.toml
    - type: bind
      source: ./volumes/tesseracts
      target: /var/lib/tesseracts/data
