[package]
name = "key_generator"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_circuit= { path = "../../lib/circuit", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_crypto = { path = "../../lib/crypto", version = "1.0" }
zksync_prover_utils = { path = "../../lib/prover_utils", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }

time = "0.1"
hex = "0.4"
rust-crypto = "0.2"
log = "0.4"
env_logger = "0.6"
structopt = "0.3.20"
handlebars = "3.0.1"
serde_json = "1.0.0"
