[package]
name = "server"
version = "0.0.1"
edition = "2018"

[dependencies]
eth_client = { path = "../../lib/eth_client", version = "0.1.0"  }
plasma = { path = "../../lib/plasma", version = "0.1.1" }
models = { path = "../../lib/models", version = "0.0.1" }
storage = { path = "../../lib/storage", version = "0.0.1" }
circuit = { path = "../../lib/circuit", version = "0.1.1"}
vlog = { path = "../../lib/vlog", version = "0.1.0"}

zksync_basic_types = { path = "../../lib/basic_types", version = "0.1.0" }
zksync_crypto = { path = "../../lib/crypto", version = "0.1.0" }
zksync_config = { path = "../../lib/config", version = "0.1.0" }
zksync_utils = { path = "../../lib/utils", version = "0.1.0" }
zksync_contracts = { path = "../../lib/contracts", version = "0.1.0" }
zksync_prover_utils = { path = "../../lib/prover_utils", version = "0.1.0" }

hex = "0.4"
ethabi = "12.0.0"
web3 = "0.13.0"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.0"
log = "0.4"
env_logger = "0.6"
itertools = "0.8"
clap = "2.33.0"
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-pubsub = "14.0.3"
jsonrpc-ws-server = "14.0.3"
jsonrpc-http-server = "14.0.3"
jsonrpc-derive = "14.0.3"

tokio = { version = "0.2", features = ["full"] }
tokio_old = { package = "tokio", version = "0.1.22" }
futures = { version = "0.3", features = ["compat"] }
actix-rt = "1.1.1"
actix-cors = "0.3.0"
actix-web = "3.0.0"
actix-web-httpauth = "0.5.0"

num = { version = "0.2", features = ["serde"] }
bigdecimal = { version = "0.1", features = ["serde"]}
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
ctrlc = { version = "3.1", features = ["termination"] }
failure = "0.1"
# TODO: should be removed after json rpc deps are updated is updated, current version (14.0)
futures01 = { package = "futures", version = "0.1" }
reqwest = { version = "0.10", features = ["blocking"] }
tiny-keccak = "1.4.2"
async-trait = "0.1.31"
prometheus_exporter_base = "0.31.0"
jsonwebtoken = "7"

rand = "0.7"

lru-cache = "0.1.2"

[dev-dependencies]
lazy_static = "1.4"
prover = { path = "../prover", version = "0.0.1" }
