# Configuration for the Ethereum sender crate

[eth_sender]

[eth_sender.sender]
# operator_private_key is defined in the `private.toml`
# operator_commit_eth_addr is defined in the `private.toml`

# Amount of confirmations required to consider L1 transaction committed.
wait_confirmations=1
# Amount of blocks we will wait before considering L1 transaction stuck.
expected_wait_time_block=30
# Node polling period in seconds.
tx_poll_period=3
# The maximum amount of simultaneously sent Ethereum transactions.
max_txs_in_flight=1
# Whether sender should interact with L1 or not.
is_enabled=true

[eth_sender.gas_price_limit]
# Gas price limit to be used by GasAdjuster until the statistics data is gathered.
# Defaults to 400 gwei (400 * 10^9 wei)
default=400000000000
# Interval between updates of the gas price limit (used by GasAdjuster) in seconds
# Defaults to 150 (avg time of 1 block is 15 seconds, thus ~10 ETH blocks)
update_interval=150
# Interval between adding the Ethereum node gas price to the GasAdjuster (in seconds).
# Defaults to 15 seconds (1 Ethereum block)
sample_interval=15
# Scale factor for gas price limit (used by GasAdjuster)
# Defaults to 1.5: every time we can increase the price by no more than 50%.
scale_factor=1.0
