[fee_ticker]
# Indicator of the API to be used for getting token prices.
# Only supported options currently are "CoinGecko" and "CoinMarketCap".
token_price_source="CoinGecko"
# Set to be a development mock server.
coinmarketcap_base_url="http://127.0.0.1:9876"
# Set to be a development mock server.
# Use https://api.coingecko.com/ for production.
coingecko_base_url="http://127.0.0.1:9876"
# Coefficient for the fee price for fast withdrawal requests.
fast_processing_coeff=10.0
# List of tokens not suitable for paying fees.
# Url to uniswap api
uniswap_url="http://127.0.0.1:9975/graphql"
# The volume of tokens to confirm their liquidity
liquidity_volume=100
# Time when liquidity check results are valid
available_liquidity_seconds=720
# List of the tokens that are unconditionally acceptable for paying fee in.
unconditionally_valid_tokens="0x0000000000000000000000000000000000000000"
token_market_update_time=120
# Number of tickers for load balancing.
number_of_ticker_actors=5
# List of tokens for which subsidions are disabled.
not_subsidized_tokens=[
    "0x2b591e99afe9f32eaa6214f7b7629768c40eeb39", # HEX
    "0x34083bbd70d394110487feaa087da875a54624ec"  # Some sample token
]

subsidized_tokens=[]
subsidized_tokens_limits=[]
