[package]
name = "zksync_eth_sender"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_eth_signer = { path = "../../lib/eth_signer", version = "1.0" }
zksync_eth_client = { path = "../../lib/eth_client", version = "1.0" }
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }

zksync_basic_types = { path = "../../lib/basic_types", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }
zksync_contracts = { path = "../../lib/contracts", version = "1.0" }

hex = "0.4"
ethabi = "12.0.0"
web3 = "0.13.0"
serde = "1.0.90"
serde_json = "1.0.0"
log = "0.4"
env_logger = "0.6"

tokio = { version = "0.2", features = ["full"] }
futures = "0.3"

num = { version = "0.2", features = ["serde"] }
ctrlc = { version = "3.1", features = ["termination"] }
anyhow = "1.0"
async-trait = "0.1.31"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
