[package]
name = "zksync_api"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[features]
default = []
api_test = []

[dependencies]
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }

zksync_crypto = { path = "../../lib/crypto", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }
zksync_contracts = { path = "../../lib/contracts", version = "1.0" }
zksync_eth_client = { path = "../../lib/eth_client", version = "1.0" }
zksync_eth_signer = { path = "../../lib/eth_signer", version = "1.0" }
zksync_api_client  = { path = "../../lib/api_client", version = "0.1" }
zksync_api_types  = { path = "../../lib/api_types", version = "1.0" }
zksync_prometheus_exporter = { path = "../../lib/prometheus_exporter", version = "1.0" }
zksync_balancer = { path = "../../lib/balancer", version = "1.0" }
zksync_gateway_watcher = { path = "../../lib/gateway_watcher", version = "1.0" }

vlog = { path = "../../lib/vlog", version = "1.0" }

hex = "0.4"
ethabi = "14.0.0"
web3 = "0.16.0"
serde = "1.0.90"
serde_json = "1.0.0"
serde_repr = "0.1"
itertools = "0.8"
jsonrpc-core = "18"
jsonrpc-core-client = {version= "18", features=["ws", "http"]}
jsonrpc-pubsub = "18.0.0"
jsonrpc-ws-server = "18"
jsonrpc-http-server = "18"
jsonrpc-derive = "18"
qstring = "0.7.2"

tokio = { version = "1", features = ["full"] }
futures = { version = "0.3", features = ["compat"] }
actix-rt = "2.2.0"
actix-cors = "0.6.0-beta.2"
rustls = "0.19.1"
actix-web = {version = "4.0.0-beta.8", features=["rustls"]}
actix-web-httpauth = "0.6.0-beta.2"
actix-files = "0.5.0"

num = { version = "0.3.1", features = ["serde"] }
bigdecimal = { version = "0.2.0", features = ["serde"]}
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
ctrlc = { version = "3.1", features = ["termination"] }
anyhow = "1.0"
thiserror = "1.0"
structopt = "0.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tiny-keccak = "1.4.2"
async-trait = "0.1"
jsonwebtoken = "7"
metrics = "0.17"
lru-cache = "0.1.2"
once_cell = "1.4"
regex = "1"

[dev-dependencies]
zksync_test_account = { path = "../../tests/test_account" }
criterion = {version =  "0.3.4", features = ["async_tokio", "async_futures"]}
actix-test = "0.1.0-beta.3"

[[bench]]
name = "api_service"
harness = false
path = "benches/criterion/lib.rs"
