[package]
name = "zksync_core"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_state = { path = "../../lib/state", version = "1.0" }
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_notifier = { path = "../../lib/notifier", version = "1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }

zksync_crypto = { path = "../../lib/crypto", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }
zksync_contracts = { path = "../../lib/contracts", version = "1.0" }
zksync_eth_client = { path = "../../lib/eth_client", version = "1.0" }
zksync_eth_signer = { path = "../../lib/eth_signer", version = "1.0" }
zksync_prometheus_exporter = { path = "../../lib/prometheus_exporter", version = "1.0" }
zksync_balancer = { path = "../../lib/balancer", version = "1.0" }
zksync_gateway_watcher = { path = "../../lib/gateway_watcher", version = "1.0" }

num = { version = "0.3.1", features = ["serde"] }

ethabi = "12.0.0"
web3 = "0.13.0"
serde = "1.0.90"
serde_json = "1.0.0"
metrics = "=0.13.0-alpha.8"
itertools = "0.9.0"

vlog = { path = "../../lib/vlog", version = "1.0", features = ["actix"] }

tokio = { version = "0.2", features = ["time"] }
futures = "0.3"
actix-rt = "1.1.1"
actix-web = "3.0.0"
reqwest = { version = "0.10", features = ["blocking", "json"] }
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
ctrlc = { version = "3.1", features = ["termination"] }
anyhow = "1.0"
thiserror = "1.0"
tiny-keccak = "1.4.2"
async-trait = "0.1"

[dev-dependencies]
num = { version = "0.3.1", features = ["serde"] }
