[package]
name = "sandbox"
version = "0.0.1"

[dependencies]
serde_json = "1.0.39"
bigdecimal = { version = "0.1.0", features = ["serde"]}
serde = "1.0.90"
serde_derive = "1.0.90"
ff = { package = "ff_ce", version = "0.6.0", features = ["derive"] }

models = { path = "../models" }
plasma = { path = "../plasma" }
