[package]
name = "storage"
version = "0.0.1"

[dependencies]
plasma = { path = "../plasma" }
models = { path = "../models" }

fnv = "1.0.6"
serde_json = "1.0.39"
serde_derive = "1.0.90"
diesel = { version = "1.4.2", features = ["postgres", "serde_json", "r2d2"] }
bigdecimal = { version = "0.1.0", features = ["serde"]}
