[package]
name = "models"
version = "0.0.1"
edition = "2018"

[dependencies]
eth_client = { path = "../eth_client" }
plasma = { path = "../plasma" }

serde = "1.0.90"
serde_derive = "1.0.90"
serde_bytes = "0.11.1"
lazy_static = "1.2.0"
