name: Publish NPM packages
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'ref or tag to publish NPM packages from'
        default: ''
        required: false

jobs:
  zksync:
    name: Publish zksync.js
    uses: matter-labs/github-workflows/.github/workflows/npm.publish-package.yaml@main
    with:
      working-directory: sdk/zksync.js
      build-command: |
        npm install
        npm run build
      ref: ${{ github.event.inputs.ref }}
    secrets:
      token: ${{ secrets.NPM_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    needs: [zksync]
    if: always() && (needs.zksync.result == 'failure' || needs.zksync.result == 'success')
    steps:
      -
        name: Notify to Mattermost (on incidents)
        uses: tferreira/matterfy@releases/v1
        with:
          type: ${{ job.zksync.result }}
          job_name: '*Publishing `${{ needs.zksync.outputs.package-name }}@${{ needs.zksync.outputs.package-version }}` ${{ needs.zksync.outputs.status }}*'
          icon_emoji: octocat
          channel: 'ci-notifications'
          url: ${{ secrets.MATTERMOST_WEBHOOK }}
