name: Publish an NPM Package

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory with the NPM package contnts
        type: string
        required: true
      build-command:
        description: Command to perform NPM pack
        type: string
        required: true
      ref:
        description: 'ref or tag to publish NPM package from'
        type: string
        required: false

    secrets:
      notify-webhook:
        description: Chat notification webhook
        required: true

jobs:
  local-call-publish:
    name: Build NPM package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      -
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      -
        name: Package info
        id: info
        uses: gregoranders/nodejs-project-info@v0.0.12
        with:
          path: ${{ inputs.working-directory }}/package.json
      -
        name: Build package
        id: build
        working-directory: ${{ inputs.working-directory }}
        run: |
          ${{ inputs.build-command }}
      -
        if: steps.build.outcome == 'success'
        name: Publish to npmjs.com
        working-directory: ${{ inputs.working-directory }}
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      -
        if: failure()
        name: Notify to Mattermost (on incidents)
        uses: tferreira/matterfy@releases/v1
        with:
          type: ${{ job.status }}
          job_name: '*Publishing `${{ steps.info.outputs.name }}` to npmjs.com did not succeed*'
          icon_emoji: octocat
          channel: 'ci-notifications'
          url: ${{ secrets.notify-webhook }}
